### PR TITLE
Add example of sub-parameter

### PR DESCRIPTION
**Pull request by Ferrari**
Add this example might help let people know them can use this kind of format to set sub-parameter.

### CODE REVIEW

**Comment by dantman** [comment]
This is a side effect of the libraries we're using. I'm not sure we want to advertise it as supported if Facebook's official client side SDK's `FB.api` does not support it.

**Comment by Ferrari** [comment]
Sorry if I misuse it, just because I could not find any example describe how to use it if we have this purpose. If it could list on Readme would be great helpful.

**Comment by dantman** [comment]
The '*correct*' way to use `fields` is the same way it's used with Facebook's own js SDK and described in the graph api documentation. And like I said, I don't feel like documenting and officially supporting something that is just a quirk.
```
GET graph.facebook.com
  /bgolub?
    fields=id,name,picture
```

It's just a comma separated string, there is nothing special about it that should require documentation.

So the proper way would just be:
```js
FB.api('/bgolub', {fields: 'id,name,picture'});
```

Or if you want to be fancy:
```js
FB.api('/bgolub', {fields: ['id', 'name', 'picture'].join(',')});
```

----

I also don't actually buy that your example results in a properly formatted graph API request.

Reviewing the library's code now, rather than a quirk of the querystring library coming into play as the array is an object it should actually be going through JSON.stringify.

Which means your example is likely making an API request to `https://graph.facebook.com/v2.1/me?fields=["id","name","picture.type(large)"]` which is not the proper way to format the `fields` header as described in the graph API documentation.

**Comment by super-ienien** [comment]
What ??? @dantman did you ever used your own library and read the facebook graph API documentation ????? what @Ferrari says is 100% valid and well documented in the API documentation

**Comment by dantman** [comment]
@super-ienien Please point me to where you see the Graph API documentation state that a JSON array is a valid value for the `fields` parameter. I've read it and haven't found anything documenting that as valid.

**Comment by super-ienien** [comment]
When I told about the Facebook API documentation it was about the sub-parameter : picture.type(large). May be i misunderstood what you are saying but i thought that you were talking about that when you said : 

> The 'correct' way to use fields is the same way it's used with Facebook's own js SDK and described in the graph api documentation. And like I said, I don't feel like documenting and officially supporting something that is just a quirk.

 But I've read your messages twice and maybe you were talking about the javascript array.
 
And I'm sorry but @Ferrari didn't write an example where he is passing a JSON array as a value for the fields parameter. He is actually passing a javascript Array wich is a feature of facebook-node (the library you are maintaining), it's already in the readme. 

Doing what he wrote in the PR make a request like this : `https://graph.facebook.com/v2.1/me?fields=id,name,picture.type(large)`. So I don't think he is wrong.

So he is right about sub-parameters (it's an official feature of the facebook api) and also right about passing an array to the fields argument (it's on your readme line 85).

Why should'nt you merge something that can help people understand how make complex requests with sub-parameters with facebook-node ?

**Comment by dantman** [comment]
Ok, there were a lot of misunderstandings and mistakes in this discussion.

* Firstly, "sub-parameter" doesn't mean anything, it's not an actual term. The Facebook documentation doesn't use it. The picture stuff is part of the "field expansion" feature described in "Making Nested Requests".
  * As this is a SDK issue not a Graph API one I looked at the diff and mistook this undefined term for "sub-parameters" as in `{ param: {...sub param...}}`.
* The README did describe the `fields` as an array, however that was wrong.
  `FB.api` behaviour **is** to JSON.stringify all object/array param values.
  The resulting request for `FB.api('me', {fields: ['id', 'name']})` is in fact `https://graph.facebook.com/v2.x/me?fields=%5B%22id%22%2C%22name%22%5D`, not `fields=id,name` and this format is not documented anywhere in the documentation as valid even though it seems to work. I've added tests and verified this behaviour.
* However even on the topic of field expansion this PR is invalid:
  * The "sub-parameters" title added to the readme is not valid terminology
  * Additionally field expansion is part of the Graph API, it's documented in the Graph API documentation. This is a Node JS SDK the README only documents how to use the SDK to make API requests to the Graph API, the Graph API itself shouldn't be documented in it.
  * The Get section this PR modifies documented 2 things: Using FB.api to make a GET api call to the Graph API without parameters and using FB.api to make a GET api call with parameters. The actual parameters themselves are immaterial. This PR add a 3rd section that was exactly the same as the second except it instead documented part of the Graph API.

Graph API documentation doesn't belong in the README. However I did modify the existing example to include the more complex picture field to give it more variety.

**Comment by super-ienien** [comment]
> Graph API documentation doesn't belong in the README. However I did modify the existing example to include the more complex picture field to give it more variety.

I agreed with this.

> The README did describe the fields as an array, however that was wrong.

Passing an array to the field parameter is a cool and usefull feature of `facebook-node` even if it's a side effect because you are using `request`. May be you shouldn't try to stick to the Facebook's official client side SDK's. It sounds like an unnecessary constraint

**Comment by dantman** [comment]
>> The README did describe the fields as an array, however that was wrong.
>
> Passing an array to the field parameter is a cool and usefull feature of facebook-node even if it's a side effect because you are using request. May be you shouldn't try to stick to the Facebook's official client side SDK's. It sounds like an unnecessary constraint

The JSON behaviour exists because other parts of the Facebook API expect JSON values, particularly the batch API.

To make that work but make `fields` a comma separated list when you use an array, I would have to special case `fields`; effectively hardcoding an implementation detail of the Graph API into the SDK. Which isn't good practice.

I've also asked the Facebook developers for some clarification on the use of a JSON in the fields parameter.

https://developers.facebook.com/bugs/1925316137705574/
> Thanks for reaching out. As far as I know, json in fields is not officially supported We may not be able to guarantee the usability of it in the future. Please use something like fields=id,name if possible.

Since the README has had an error in it this whole time and people copied it, when I have some time I'll add a warning specific to that error (`fields` parameter as an array) when you do that.

**Pull request closed without merging**
